# Generated by Django 2.2.20 on 2021-07-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.CharField(max_length=256)),
                ('comedian', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jokes_comedian', to='home.Comedians')),
            ],
        ),
        migrations.AddField(
            model_name='comedians',
            name='cname',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comedians_cname', to='home.Jokes'),
        ),
    ]
