# Generated by Django 2.2.20 on 2021-07-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210707_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedians',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='jokes',
            name='comedian',
        ),
        migrations.AddField(
            model_name='comedians',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
